# Generated by Django 6.1 on 2026-09-24 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='time_limit',
            field=models.IntegerField(default=30, help_text='Duration in minutes'),
        ),
    ]
